    // Alumni [fixed order based on time of lab affiliation, most recent first]
    // Add new alumni to the start of these lists; students will be rendered
    
var alumni_ugms = [
    {
        "full_names": "Chenfeng Huang",
        "display_names": "Chenfeng Huang",
        "year": "Masters @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Ishika Singh",
        "next": "",
        "link_anchors": ""
    },    
    {
        "full_names": "Wilbert Pumacay Huallpa",
        "display_names": "Wilbert Pumacay",
        "year": "Masters @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "https://arxiv.org/abs/2402.08191",
        "phd_mentor": "Ishika Singh",
        "next": "",
        "link_anchors": ""
    },    
    {
        "full_names": "Riley Ashford",
        "display_names": "Riley Ashford",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Leticia Pinto-Alva",
        "next": "",
        "link_anchors": ""
    },    
    {
        "full_names": "Cecily Chung",
        "display_names": "Cecily Chung",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Leticia Pinto-Alva",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Gwen Bradforth",
        "display_names": "Gwen Bradforth",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Leticia Pinto-Alva",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Emmanuel Ezirim",
        "display_names": "Emmanuel Ezirim",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Tejas Srinivasan",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Miaosen Chai",
        "display_names": "Miaosen Chai",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Tejas Srinivasan",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Aarav Monga",
        "display_names": "Aarav Monga",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Spring 2024",
        "websites": "",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "https://arxiv.org/abs/2302.14030",
        "phd_mentor": "Tejas Srinivasan",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Jaiv Doshi",
        "display_names": "Jaiv Doshi",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Anthony Liang",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "James (Yuxi) Qian",
        "display_names": "James (Yuxi) Qian",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2023 - Spring 2024",
        "websites": "",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Anthony Liang",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Flora Jia",
        "display_names": "Flora Jia",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Spring 2024",
        "websites": "https://flora-jia-jfr.github.io/about/",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Tejas Srinivasan",
        "next": "PhD in Computer Science, Duke University",
        "link_anchors": ""
    },
    {
        "full_names": "Allen Chang",
        "display_names": "Allen Chang",
        "year": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Spring 2023",
        "websites": "https://www.cylumn.com/",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "https://arxiv.org/abs/2302.14030",
        "phd_mentor": "Tejas Srinivasan",
        "next": "PhD in Computer and Information Science, UPenn, with an <a href=\"https://www.nsfgrfp.org/\">NSF Graduate Research Fellowship</a>",
        "link_anchors": ""
    },
    {
        "full_names": "Riley Carlin",
        "display_names": "Riley Carlin",
        "affiliation": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Spring 2023",
        "websites": "https://www.linkedin.com/in/riley-carlin/",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "https://www.esann.org/sites/default/files/proceedings/2023/ES2023-83.pdf",
        "phd_mentor": "Lee Kezar",
        "next": "PhD in Statistics, Columbia University",
        "link_anchors": ""
    },
    {
        "full_names": "Yuan Huang",
        "display_names": "Yuan Huang",
        "affiliation": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Fall 2023",
        "websites": "https://yuanhuanghuang.github.io/",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Bill Zhu",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Elle Szabo",
        "display_names": "Elle Szabo",
        "affiliation": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Summer 2023",
        "websites": "",
        "program": "",
        "program_link": "",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Abrar Anwar",
        "next": "",
        "link_anchors": ""
    },
    {
        "full_names": "Chu Fang",
        "display_names": "Chu Fang",
        "affiliation": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Spring 2023",
        "websites": "",
        "program": "URAP Program",
        "program_link": "https://undergrad.usc.edu/faculty/urap/",
        "project_title": "",
        "project_deliverable": "",
        "next": "",
        "phd_mentor": "Leticia Pinto-Alva"
    },
    {
        "full_names": "Julie Kim",
        "display_names": "Julie Kim",
        "affiliation": "Undergraduate @ USC",
        "visit_period": "Fall 2022 - Spring 2023",
        "websites": "",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "A Machine Learning-Based ADRD Screening Tool",
        "project_deliverable": "https://uscinteractionlab.web.app/project/ADRD",
        "next": "",
        "phd_mentor": "Leticia Pinto-Alva"
    },
    {
        "full_names": "Junu Song",
        "display_names": "Junu Song",
        "affiliation": "Undergraduate @ USC",
        "visit_period": "Fall 2022",
        "websites": "",
        "program": "CURVE Fellowship",
        "program_link": "https://viterbiundergrad.usc.edu/research/curve/",
        "project_title": "",
        "project_deliverable": "",
        "phd_mentor": "Anthony Liang",
        "next": "",
        "link_anchors": "2022junu"
    },

]
